stages:
  - build
  - docker
  - deploy
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - complete/build
build:
  stage: build
  script:
    - export AWS_PROFILE=l2f
    - aws ec2 describe-subnets
    - whoami
    - ls -altr
    - cd complete
    - ./gradlew build
  artifacts:
    paths:
      - complete/build
docker build:
  stage: docker
  script:
    - cd complete
    - export AWS_PROFILE=l2f
    - docker login -u AWS -p $(aws ecr get-login-password --region us-west-2) 698579318444.dkr.ecr.us-west-2.amazonaws.com
    - docker build -t gs-boot .
    - docker tag gs-boot:latest 698579318444.dkr.ecr.us-west-2.amazonaws.com/gs-boot:latest
    - docker push 698579318444.dkr.ecr.us-west-2.amazonaws.com/gs-boot:latest
eks deploy:
  stage: deploy
  script:
    - git clone git@github.com:codelkirby/helm-charts.git
    - cd helm-charts
    - /opt/gitlab-scripts/helm_deploy.sh
