stages:
  - build
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - complete/build/
build:
  stage: build
  image: openjdk:16-alpine
  script:
    - cd complete
    - ls
    - ./gradlew build
  artifacts:
    paths:
      - complete/build