stages:
  - build
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - complete/build
build:
  stage: build
  script:
    - export AWS_PROFILE=l2f
    - aws ec2 describe-subnets
    - whoami
    - ls -altr
    - cd complete
    - ./gradlew build
  artifacts:
    paths:
      - complete/build